<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version3_0_2_0 extends AbstractMigration
{

    public function up(Schema $schema)
    {
        if ($this->connection->getDatabasePlatform()->getName() === "postgresql") {
            $this->addSql("CREATE SEQUENCE fom_user_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE fom_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_core_contact_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_core_keyword_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_core_layerset_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_core_srs_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_core_sourceinstance_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_core_state_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_core_element_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_core_source_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_core_application_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_wmc_wmc_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_wms_wmsinstancelayer_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE mb_wms_wmslayersource_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE SEQUENCE owsproxy_log_id_seq INCREMENT BY 1 MINVALUE 1 START 1");
            $this->addSql("CREATE TABLE fom_profile_basic (uid_id INT NOT NULL, firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) DEFAULT NULL, notes TEXT DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, zipCode VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, organizationName VARCHAR(255) DEFAULT NULL, organizationRole VARCHAR(255) DEFAULT NULL, PRIMARY KEY(uid_id))");
            $this->addSql("CREATE TABLE fom_user (id INT NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, registrationTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, registrationToken VARCHAR(50) DEFAULT NULL, resetTime TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, resetToken VARCHAR(50) DEFAULT NULL, loginFailed TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, loginFailCount INT DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_ACA60792F85E0677 ON fom_user (username)");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_ACA60792E7927C74 ON fom_user (email)");
            $this->addSql("CREATE TABLE fom_users_groups (user_id INT NOT NULL, group_id INT NOT NULL, PRIMARY KEY(user_id, group_id))");
            $this->addSql("CREATE INDEX IDX_15F45F1A76ED395 ON fom_users_groups (user_id)");
            $this->addSql("CREATE INDEX IDX_15F45F1FE54D947 ON fom_users_groups (group_id)");
            $this->addSql("CREATE TABLE fom_group (id INT NOT NULL, title VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_7CE07A482B36786B ON fom_group (title)");
            $this->addSql("CREATE TABLE mb_core_contact (id INT NOT NULL, person VARCHAR(255) DEFAULT NULL, position VARCHAR(255) DEFAULT NULL, organization VARCHAR(255) DEFAULT NULL, voiceTelephone VARCHAR(255) DEFAULT NULL, facsimileTelephone VARCHAR(255) DEFAULT NULL, electronicMailAddress VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, addressType VARCHAR(255) DEFAULT NULL, addressCity VARCHAR(255) DEFAULT NULL, addressStateOrProvince VARCHAR(255) DEFAULT NULL, addressPostCode VARCHAR(255) DEFAULT NULL, addressCountry VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE TABLE mb_core_keyword (id INT NOT NULL, value VARCHAR(255) NOT NULL, sourceid INT NOT NULL, sourceclass VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE TABLE mb_core_layerset (id INT NOT NULL, application_id INT DEFAULT NULL, title VARCHAR(128) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_9D1A22923E030ACD ON mb_core_layerset (application_id)");
            $this->addSql("CREATE UNIQUE INDEX layerset_idx ON mb_core_layerset (application_id, title)");
            $this->addSql("CREATE TABLE mb_core_srs (id INT NOT NULL, name VARCHAR(15) NOT NULL, title VARCHAR(128) NOT NULL, definition VARCHAR(512) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_AD400D955E237E06 ON mb_core_srs (name)");
            $this->addSql("CREATE TABLE mb_core_sourceinstance (id INT NOT NULL, layerset INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, weight INT NOT NULL, enabled BOOLEAN DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_688D0B496A3B1D21 ON mb_core_sourceinstance (layerset)");
            $this->addSql("CREATE TABLE mb_core_state (id INT NOT NULL, title VARCHAR(128) DEFAULT NULL, serverurl VARCHAR(1024) DEFAULT NULL, slug VARCHAR(128) DEFAULT NULL, json TEXT DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE TABLE mb_core_element (id INT NOT NULL, application_id INT DEFAULT NULL, title VARCHAR(128) NOT NULL, class VARCHAR(1024) NOT NULL, configuration TEXT DEFAULT NULL, region VARCHAR(255) NOT NULL, enabled BOOLEAN DEFAULT NULL, weight INT NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_228B0AD3E030ACD ON mb_core_element (application_id)");
            $this->addSql("COMMENT ON COLUMN mb_core_element.configuration IS '(DC2Type:array)'");
            $this->addSql("CREATE TABLE mb_core_source (id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, alias VARCHAR(128) DEFAULT NULL, description TEXT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE TABLE mb_core_application (id INT NOT NULL, owner_id INT DEFAULT NULL, title VARCHAR(128) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, template VARCHAR(1024) NOT NULL, published BOOLEAN NOT NULL, screenshot VARCHAR(256) DEFAULT NULL, extra_assets TEXT DEFAULT NULL, updated TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_77F4A71D2B36786B ON mb_core_application (title)");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_77F4A71D989D9B62 ON mb_core_application (slug)");
            $this->addSql("CREATE INDEX IDX_77F4A71D7E3C61F9 ON mb_core_application (owner_id)");
            $this->addSql("COMMENT ON COLUMN mb_core_application.extra_assets IS '(DC2Type:array)'");
            $this->addSql("CREATE TABLE mb_wmc_wmc (id INT NOT NULL, state INT DEFAULT NULL, contact_id INT DEFAULT NULL, version VARCHAR(10) DEFAULT NULL, wmcid VARCHAR(255) DEFAULT NULL, keywords TEXT DEFAULT NULL, abstract TEXT DEFAULT NULL, logourl TEXT DEFAULT NULL, descriptionurl TEXT DEFAULT NULL, screenshotPath VARCHAR(255) DEFAULT NULL, public BOOLEAN DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_BC0F146BA393D2FB ON mb_wmc_wmc (state)");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_BC0F146BE7A1254A ON mb_wmc_wmc (contact_id)");
            $this->addSql("COMMENT ON COLUMN mb_wmc_wmc.keywords IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wmc_wmc.logourl IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wmc_wmc.descriptionurl IS '(DC2Type:object)'");
            $this->addSql("CREATE TABLE mb_wms_wmsinstancelayer (id INT NOT NULL, wmsinstance INT DEFAULT NULL, wmslayersource INT DEFAULT NULL, parent INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, active BOOLEAN DEFAULT NULL, allowselected BOOLEAN DEFAULT NULL, selected BOOLEAN DEFAULT NULL, info BOOLEAN DEFAULT NULL, allowinfo BOOLEAN DEFAULT NULL, toggle BOOLEAN DEFAULT NULL, allowtoggle BOOLEAN DEFAULT NULL, allowreorder BOOLEAN DEFAULT NULL, minScale DOUBLE PRECISION DEFAULT NULL, maxScale DOUBLE PRECISION DEFAULT NULL, style VARCHAR(255) DEFAULT NULL, priority INT DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_38F34DB176BBE8FB ON mb_wms_wmsinstancelayer (wmsinstance)");
            $this->addSql("CREATE INDEX IDX_38F34DB1714D2654 ON mb_wms_wmsinstancelayer (wmslayersource)");
            $this->addSql("CREATE INDEX IDX_38F34DB13D8E604F ON mb_wms_wmsinstancelayer (parent)");
            $this->addSql("CREATE TABLE mb_wms_wmssource (id INT NOT NULL, contact_id INT DEFAULT NULL, originUrl VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, version VARCHAR(255) DEFAULT NULL, onlineResource VARCHAR(255) DEFAULT NULL, fees TEXT DEFAULT NULL, accessConstraints TEXT DEFAULT NULL, layerLimit INT DEFAULT NULL, maxWidth INT DEFAULT NULL, maxHeight INT DEFAULT NULL, exceptionFormats TEXT DEFAULT NULL, supportSld BOOLEAN DEFAULT NULL, userLayer BOOLEAN DEFAULT NULL, userStyle BOOLEAN DEFAULT NULL, remoteWfs BOOLEAN DEFAULT NULL, inlineFeature BOOLEAN DEFAULT NULL, remoteWcs BOOLEAN DEFAULT NULL, getCapabilities TEXT DEFAULT NULL, getMap TEXT DEFAULT NULL, getFeatureInfo TEXT DEFAULT NULL, describeLayer TEXT DEFAULT NULL, getLegendGraphic TEXT DEFAULT NULL, getStyles TEXT DEFAULT NULL, putStyles TEXT DEFAULT NULL, username VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_F5D6FE8FE7A1254A ON mb_wms_wmssource (contact_id)");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.exceptionFormats IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.getCapabilities IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.getMap IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.getFeatureInfo IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.describeLayer IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.getLegendGraphic IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.getStyles IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.putStyles IS '(DC2Type:object)'");
            $this->addSql("CREATE TABLE mb_wms_wmsinstance (id INT NOT NULL, wmssource INT DEFAULT NULL, configuration TEXT DEFAULT NULL, srs VARCHAR(255) DEFAULT NULL, format VARCHAR(255) DEFAULT NULL, infoformat VARCHAR(255) DEFAULT NULL, exceptionformat VARCHAR(255) DEFAULT NULL, transparency BOOLEAN DEFAULT NULL, visible BOOLEAN DEFAULT NULL, opacity INT DEFAULT NULL, proxy BOOLEAN DEFAULT NULL, tiled BOOLEAN DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_60860685AED1BBE ON mb_wms_wmsinstance (wmssource)");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmsinstance.configuration IS '(DC2Type:array)'");
            $this->addSql("CREATE TABLE mb_wms_wmslayersource (id INT NOT NULL, wmssource INT DEFAULT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, abstract TEXT DEFAULT NULL, queryable BOOLEAN DEFAULT NULL, cascaded INT DEFAULT NULL, opaque BOOLEAN DEFAULT NULL, noSubset BOOLEAN DEFAULT NULL, fixedWidth INT DEFAULT NULL, fixedHeight INT DEFAULT NULL, latlonBounds TEXT DEFAULT NULL, boundingBoxes TEXT DEFAULT NULL, srs TEXT DEFAULT NULL, styles TEXT DEFAULT NULL, scale TEXT DEFAULT NULL, scaleHint TEXT DEFAULT NULL, attribution TEXT DEFAULT NULL, identifier TEXT DEFAULT NULL, authority TEXT DEFAULT NULL, metadataUrl TEXT DEFAULT NULL, dimension TEXT DEFAULT NULL, extent TEXT DEFAULT NULL, dataUrl TEXT DEFAULT NULL, featureListUrl TEXT DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_B7B7F16BAED1BBE ON mb_wms_wmslayersource (wmssource)");
            $this->addSql("CREATE INDEX IDX_B7B7F16B727ACA70 ON mb_wms_wmslayersource (parent_id)");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.latlonBounds IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.boundingBoxes IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.srs IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.styles IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.scale IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.scaleHint IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.attribution IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.identifier IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.authority IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.metadataUrl IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.dimension IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.extent IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.dataUrl IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.featureListUrl IS '(DC2Type:array)'");
            $this->addSql("CREATE TABLE owsproxy_log (id INT NOT NULL, username VARCHAR(512) NOT NULL, roles TEXT NOT NULL, ip VARCHAR(40) NOT NULL, timestamp TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, request_url TEXT NOT NULL, request_body TEXT NOT NULL, request_method VARCHAR(255) NOT NULL, response_mimetype VARCHAR(255) NOT NULL, response_code INT NOT NULL, response_size INT NOT NULL, PRIMARY KEY(id))");
            $this->addSql("ALTER TABLE fom_profile_basic ADD CONSTRAINT FK_DE31F81534B549B FOREIGN KEY (uid_id) REFERENCES fom_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE fom_users_groups ADD CONSTRAINT FK_15F45F1A76ED395 FOREIGN KEY (user_id) REFERENCES fom_user (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE fom_users_groups ADD CONSTRAINT FK_15F45F1FE54D947 FOREIGN KEY (group_id) REFERENCES fom_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_core_layerset ADD CONSTRAINT FK_9D1A22923E030ACD FOREIGN KEY (application_id) REFERENCES mb_core_application (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_core_sourceinstance ADD CONSTRAINT FK_688D0B496A3B1D21 FOREIGN KEY (layerset) REFERENCES mb_core_layerset (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_core_element ADD CONSTRAINT FK_228B0AD3E030ACD FOREIGN KEY (application_id) REFERENCES mb_core_application (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_core_application ADD CONSTRAINT FK_77F4A71D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES fom_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wmc_wmc ADD CONSTRAINT FK_BC0F146BA393D2FB FOREIGN KEY (state) REFERENCES mb_core_state (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wmc_wmc ADD CONSTRAINT FK_BC0F146BE7A1254A FOREIGN KEY (contact_id) REFERENCES mb_core_contact (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer ADD CONSTRAINT FK_38F34DB176BBE8FB FOREIGN KEY (wmsinstance) REFERENCES mb_wms_wmsinstance (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer ADD CONSTRAINT FK_38F34DB1714D2654 FOREIGN KEY (wmslayersource) REFERENCES mb_wms_wmslayersource (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer ADD CONSTRAINT FK_38F34DB13D8E604F FOREIGN KEY (parent) REFERENCES mb_wms_wmsinstancelayer (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wms_wmssource ADD CONSTRAINT FK_F5D6FE8FE7A1254A FOREIGN KEY (contact_id) REFERENCES mb_core_contact (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wms_wmssource ADD CONSTRAINT FK_F5D6FE8FBF396750 FOREIGN KEY (id) REFERENCES mb_core_source (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance ADD CONSTRAINT FK_60860685AED1BBE FOREIGN KEY (wmssource) REFERENCES mb_wms_wmssource (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance ADD CONSTRAINT FK_60860685BF396750 FOREIGN KEY (id) REFERENCES mb_core_sourceinstance (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource ADD CONSTRAINT FK_B7B7F16BAED1BBE FOREIGN KEY (wmssource) REFERENCES mb_wms_wmssource (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource ADD CONSTRAINT FK_B7B7F16B727ACA70 FOREIGN KEY (parent_id) REFERENCES mb_wms_wmslayersource (id) NOT DEFERRABLE INITIALLY IMMEDIATE");
        } else if ($this->connection->getDatabasePlatform()->getName() === "oracle") {
            $this->addSql("CREATE SEQUENCE fom_user_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE fom_group_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_core_contact_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_core_keyword_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_core_layerset_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_core_srs_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_core_sourceinstance_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_core_state_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_core_element_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_core_source_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_core_application_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_wmc_wmc_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_wms_wmsinstancelayer_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE mb_wms_wmslayersource_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE SEQUENCE owsproxy_log_id_seq START WITH 1 MINVALUE 1 INCREMENT BY 1");
            $this->addSql("CREATE TABLE fom_profile_basic (uid_id NUMBER(10) NOT NULL, firstName VARCHAR2(255) DEFAULT NULL, lastName VARCHAR2(255) DEFAULT NULL, notes CLOB DEFAULT NULL, phone VARCHAR2(255) DEFAULT NULL, street VARCHAR2(255) DEFAULT NULL, zipCode VARCHAR2(255) DEFAULT NULL, city VARCHAR2(255) DEFAULT NULL, country VARCHAR2(255) DEFAULT NULL, organizationName VARCHAR2(255) DEFAULT NULL, organizationRole VARCHAR2(255) DEFAULT NULL, PRIMARY KEY(uid_id))");
            $this->addSql("CREATE TABLE fom_user (id NUMBER(10) NOT NULL, username VARCHAR2(255) NOT NULL, email VARCHAR2(255) NOT NULL, password VARCHAR2(255) NOT NULL, salt VARCHAR2(255) NOT NULL, registrationTime TIMESTAMP(0) DEFAULT NULL, registrationToken VARCHAR2(50) DEFAULT NULL, resetTime TIMESTAMP(0) DEFAULT NULL, resetToken VARCHAR2(50) DEFAULT NULL, loginFailed TIMESTAMP(0) DEFAULT NULL, loginFailCount NUMBER(10) DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_ACA60792F85E0677 ON fom_user (username)");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_ACA60792E7927C74 ON fom_user (email)");
            $this->addSql("CREATE TABLE fom_users_groups (user_id NUMBER(10) NOT NULL, group_id NUMBER(10) NOT NULL, PRIMARY KEY(user_id, group_id))");
            $this->addSql("CREATE INDEX IDX_15F45F1A76ED395 ON fom_users_groups (user_id)");
            $this->addSql("CREATE INDEX IDX_15F45F1FE54D947 ON fom_users_groups (group_id)");
            $this->addSql("CREATE TABLE fom_group (id NUMBER(10) NOT NULL, title VARCHAR2(255) NOT NULL, description CLOB DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_7CE07A482B36786B ON fom_group (title)");
            $this->addSql("CREATE TABLE mb_core_contact (id NUMBER(10) NOT NULL, person VARCHAR2(255) DEFAULT NULL, position VARCHAR2(255) DEFAULT NULL, organization VARCHAR2(255) DEFAULT NULL, voiceTelephone VARCHAR2(255) DEFAULT NULL, facsimileTelephone VARCHAR2(255) DEFAULT NULL, electronicMailAddress VARCHAR2(255) DEFAULT NULL, address VARCHAR2(255) DEFAULT NULL, addressType VARCHAR2(255) DEFAULT NULL, addressCity VARCHAR2(255) DEFAULT NULL, addressStateOrProvince VARCHAR2(255) DEFAULT NULL, addressPostCode VARCHAR2(255) DEFAULT NULL, addressCountry VARCHAR2(255) DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE TABLE mb_core_keyword (id NUMBER(10) NOT NULL, value VARCHAR2(255) NOT NULL, sourceid NUMBER(10) NOT NULL, sourceclass VARCHAR2(255) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE TABLE mb_core_layerset (id NUMBER(10) NOT NULL, application_id NUMBER(10) DEFAULT NULL, title VARCHAR2(128) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_9D1A22923E030ACD ON mb_core_layerset (application_id)");
            $this->addSql("CREATE UNIQUE INDEX layerset_idx ON mb_core_layerset (application_id, title)");
            $this->addSql("CREATE TABLE mb_core_srs (id NUMBER(10) NOT NULL, name VARCHAR2(15) NOT NULL, title VARCHAR2(128) NOT NULL, definition VARCHAR2(512) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_AD400D955E237E06 ON mb_core_srs (name)");
            $this->addSql("CREATE TABLE mb_core_sourceinstance (id NUMBER(10) NOT NULL, layerset NUMBER(10) DEFAULT NULL, title VARCHAR2(255) DEFAULT NULL, weight NUMBER(10) NOT NULL, enabled NUMBER(1) DEFAULT NULL, discr VARCHAR2(255) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_688D0B496A3B1D21 ON mb_core_sourceinstance (layerset)");
            $this->addSql("CREATE TABLE mb_core_state (id NUMBER(10) NOT NULL, title VARCHAR2(128) DEFAULT NULL, serverurl VARCHAR2(1024) DEFAULT NULL, slug VARCHAR2(128) DEFAULT NULL, json CLOB DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE TABLE mb_core_element (id NUMBER(10) NOT NULL, application_id NUMBER(10) DEFAULT NULL, title VARCHAR2(128) NOT NULL, class VARCHAR2(1024) NOT NULL, configuration CLOB DEFAULT NULL, region VARCHAR2(255) NOT NULL, enabled NUMBER(1) DEFAULT NULL, weight NUMBER(10) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_228B0AD3E030ACD ON mb_core_element (application_id)");
            $this->addSql("COMMENT ON COLUMN mb_core_element.configuration IS '(DC2Type:array)'");
            $this->addSql("CREATE TABLE mb_core_source (id NUMBER(10) NOT NULL, title VARCHAR2(255) DEFAULT NULL, alias VARCHAR2(128) DEFAULT NULL, description CLOB DEFAULT NULL, discr VARCHAR2(255) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE TABLE mb_core_application (id NUMBER(10) NOT NULL, owner_id NUMBER(10) DEFAULT NULL, title VARCHAR2(128) NOT NULL, slug VARCHAR2(255) NOT NULL, description CLOB DEFAULT NULL, template VARCHAR2(1024) NOT NULL, published NUMBER(1) NOT NULL, screenshot VARCHAR2(256) DEFAULT NULL, extra_assets CLOB DEFAULT NULL, updated TIMESTAMP(0) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_77F4A71D2B36786B ON mb_core_application (title)");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_77F4A71D989D9B62 ON mb_core_application (slug)");
            $this->addSql("CREATE INDEX IDX_77F4A71D7E3C61F9 ON mb_core_application (owner_id)");
            $this->addSql("COMMENT ON COLUMN mb_core_application.extra_assets IS '(DC2Type:array)'");
            $this->addSql('CREATE TABLE mb_wmc_wmc (id NUMBER(10) NOT NULL, state NUMBER(10) DEFAULT NULL, contact_id NUMBER(10) DEFAULT NULL, version VARCHAR2(10) DEFAULT NULL, wmcid VARCHAR2(255) DEFAULT NULL, keywords CLOB DEFAULT NULL, abstract CLOB DEFAULT NULL, logourl CLOB DEFAULT NULL, descriptionurl CLOB DEFAULT NULL, screenshotPath VARCHAR2(255) DEFAULT NULL, "public" NUMBER(1) DEFAULT NULL, PRIMARY KEY(id))');
            $this->addSql("CREATE UNIQUE INDEX UNIQ_BC0F146BA393D2FB ON mb_wmc_wmc (state)");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_BC0F146BE7A1254A ON mb_wmc_wmc (contact_id)");
            $this->addSql("COMMENT ON COLUMN mb_wmc_wmc.keywords IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wmc_wmc.logourl IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wmc_wmc.descriptionurl IS '(DC2Type:object)'");
            $this->addSql("CREATE TABLE mb_wms_wmsinstancelayer (id NUMBER(10) NOT NULL, wmsinstance NUMBER(10) DEFAULT NULL, wmslayersource NUMBER(10) DEFAULT NULL, parent NUMBER(10) DEFAULT NULL, title VARCHAR2(255) DEFAULT NULL, active NUMBER(1) DEFAULT NULL, allowselected NUMBER(1) DEFAULT NULL, selected NUMBER(1) DEFAULT NULL, info NUMBER(1) DEFAULT NULL, allowinfo NUMBER(1) DEFAULT NULL, toggle NUMBER(1) DEFAULT NULL, allowtoggle NUMBER(1) DEFAULT NULL, allowreorder NUMBER(1) DEFAULT NULL, minScale DOUBLE PRECISION DEFAULT NULL, maxScale DOUBLE PRECISION DEFAULT NULL, style VARCHAR2(255) DEFAULT NULL, priority NUMBER(10) DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_38F34DB176BBE8FB ON mb_wms_wmsinstancelayer (wmsinstance)");
            $this->addSql("CREATE INDEX IDX_38F34DB1714D2654 ON mb_wms_wmsinstancelayer (wmslayersource)");
            $this->addSql("CREATE INDEX IDX_38F34DB13D8E604F ON mb_wms_wmsinstancelayer (parent)");
            $this->addSql("CREATE TABLE mb_wms_wmssource (id NUMBER(10) NOT NULL, contact_id NUMBER(10) DEFAULT NULL, originUrl VARCHAR2(255) DEFAULT NULL, name VARCHAR2(255) DEFAULT NULL, version VARCHAR2(255) DEFAULT NULL, onlineResource VARCHAR2(255) DEFAULT NULL, fees CLOB DEFAULT NULL, accessConstraints CLOB DEFAULT NULL, layerLimit NUMBER(10) DEFAULT NULL, maxWidth NUMBER(10) DEFAULT NULL, maxHeight NUMBER(10) DEFAULT NULL, exceptionFormats CLOB DEFAULT NULL, supportSld NUMBER(1) DEFAULT NULL, userLayer NUMBER(1) DEFAULT NULL, userStyle NUMBER(1) DEFAULT NULL, remoteWfs NUMBER(1) DEFAULT NULL, inlineFeature NUMBER(1) DEFAULT NULL, remoteWcs NUMBER(1) DEFAULT NULL, getCapabilities CLOB DEFAULT NULL, getMap CLOB DEFAULT NULL, getFeatureInfo CLOB DEFAULT NULL, describeLayer CLOB DEFAULT NULL, getLegendGraphic CLOB DEFAULT NULL, getStyles CLOB DEFAULT NULL, putStyles CLOB DEFAULT NULL, username VARCHAR2(255) DEFAULT NULL, password VARCHAR2(255) DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE UNIQUE INDEX UNIQ_F5D6FE8FE7A1254A ON mb_wms_wmssource (contact_id)");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.exceptionFormats IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.getCapabilities IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.getMap IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.getFeatureInfo IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.describeLayer IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.getLegendGraphic IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.getStyles IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmssource.putStyles IS '(DC2Type:object)'");
            $this->addSql("CREATE TABLE mb_wms_wmsinstance (id NUMBER(10) NOT NULL, wmssource NUMBER(10) DEFAULT NULL, configuration CLOB DEFAULT NULL, srs VARCHAR2(255) DEFAULT NULL, format VARCHAR2(255) DEFAULT NULL, infoformat VARCHAR2(255) DEFAULT NULL, exceptionformat VARCHAR2(255) DEFAULT NULL, transparency NUMBER(1) DEFAULT NULL, visible NUMBER(1) DEFAULT NULL, opacity NUMBER(10) DEFAULT NULL, proxy NUMBER(1) DEFAULT NULL, tiled NUMBER(1) DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_60860685AED1BBE ON mb_wms_wmsinstance (wmssource)");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmsinstance.configuration IS '(DC2Type:array)'");
            $this->addSql("CREATE TABLE mb_wms_wmslayersource (id NUMBER(10) NOT NULL, wmssource NUMBER(10) DEFAULT NULL, parent_id NUMBER(10) DEFAULT NULL, name VARCHAR2(255) DEFAULT NULL, title VARCHAR2(255) DEFAULT NULL, abstract CLOB DEFAULT NULL, queryable NUMBER(1) DEFAULT NULL, cascaded NUMBER(10) DEFAULT NULL, opaque NUMBER(1) DEFAULT NULL, noSubset NUMBER(1) DEFAULT NULL, fixedWidth NUMBER(10) DEFAULT NULL, fixedHeight NUMBER(10) DEFAULT NULL, latlonBounds CLOB DEFAULT NULL, boundingBoxes CLOB DEFAULT NULL, srs CLOB DEFAULT NULL, styles CLOB DEFAULT NULL, scale CLOB DEFAULT NULL, scaleHint CLOB DEFAULT NULL, attribution CLOB DEFAULT NULL, identifier CLOB DEFAULT NULL, authority CLOB DEFAULT NULL, metadataUrl CLOB DEFAULT NULL, dimension CLOB DEFAULT NULL, extent CLOB DEFAULT NULL, dataUrl CLOB DEFAULT NULL, featureListUrl CLOB DEFAULT NULL, PRIMARY KEY(id))");
            $this->addSql("CREATE INDEX IDX_B7B7F16BAED1BBE ON mb_wms_wmslayersource (wmssource)");
            $this->addSql("CREATE INDEX IDX_B7B7F16B727ACA70 ON mb_wms_wmslayersource (parent_id)");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.latlonBounds IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.boundingBoxes IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.srs IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.styles IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.scale IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.scaleHint IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.attribution IS '(DC2Type:object)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.identifier IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.authority IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.metadataUrl IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.dimension IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.extent IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.dataUrl IS '(DC2Type:array)'");
            $this->addSql("COMMENT ON COLUMN mb_wms_wmslayersource.featureListUrl IS '(DC2Type:array)'");
            $this->addSql("CREATE TABLE owsproxy_log (id NUMBER(10) NOT NULL, username VARCHAR2(512) NOT NULL, roles CLOB NOT NULL, ip VARCHAR2(40) NOT NULL, timestamp TIMESTAMP(0) NOT NULL, request_url CLOB NOT NULL, request_body CLOB NOT NULL, request_method VARCHAR2(255) NOT NULL, response_mimetype VARCHAR2(255) NOT NULL, response_code NUMBER(10) NOT NULL, response_size NUMBER(10) NOT NULL, PRIMARY KEY(id))");
            $this->addSql("ALTER TABLE fom_profile_basic ADD CONSTRAINT FK_DE31F81534B549B FOREIGN KEY (uid_id) REFERENCES fom_user (id)");
            $this->addSql("ALTER TABLE fom_users_groups ADD CONSTRAINT FK_15F45F1A76ED395 FOREIGN KEY (user_id) REFERENCES fom_user (id) ON DELETE CASCADE");
            $this->addSql("ALTER TABLE fom_users_groups ADD CONSTRAINT FK_15F45F1FE54D947 FOREIGN KEY (group_id) REFERENCES fom_group (id) ON DELETE CASCADE");
            $this->addSql("ALTER TABLE mb_core_layerset ADD CONSTRAINT FK_9D1A22923E030ACD FOREIGN KEY (application_id) REFERENCES mb_core_application (id)");
            $this->addSql("ALTER TABLE mb_core_sourceinstance ADD CONSTRAINT FK_688D0B496A3B1D21 FOREIGN KEY (layerset) REFERENCES mb_core_layerset (id)");
            $this->addSql("ALTER TABLE mb_core_element ADD CONSTRAINT FK_228B0AD3E030ACD FOREIGN KEY (application_id) REFERENCES mb_core_application (id)");
            $this->addSql("ALTER TABLE mb_core_application ADD CONSTRAINT FK_77F4A71D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES fom_user (id)");
            $this->addSql("ALTER TABLE mb_wmc_wmc ADD CONSTRAINT FK_BC0F146BA393D2FB FOREIGN KEY (state) REFERENCES mb_core_state (id)");
            $this->addSql("ALTER TABLE mb_wmc_wmc ADD CONSTRAINT FK_BC0F146BE7A1254A FOREIGN KEY (contact_id) REFERENCES mb_core_contact (id)");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer ADD CONSTRAINT FK_38F34DB176BBE8FB FOREIGN KEY (wmsinstance) REFERENCES mb_wms_wmsinstance (id)");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer ADD CONSTRAINT FK_38F34DB1714D2654 FOREIGN KEY (wmslayersource) REFERENCES mb_wms_wmslayersource (id)");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer ADD CONSTRAINT FK_38F34DB13D8E604F FOREIGN KEY (parent) REFERENCES mb_wms_wmsinstancelayer (id)");
            $this->addSql("ALTER TABLE mb_wms_wmssource ADD CONSTRAINT FK_F5D6FE8FE7A1254A FOREIGN KEY (contact_id) REFERENCES mb_core_contact (id)");
            $this->addSql("ALTER TABLE mb_wms_wmssource ADD CONSTRAINT FK_F5D6FE8FBF396750 FOREIGN KEY (id) REFERENCES mb_core_source (id) ON DELETE CASCADE");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance ADD CONSTRAINT FK_60860685AED1BBE FOREIGN KEY (wmssource) REFERENCES mb_wms_wmssource (id)");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance ADD CONSTRAINT FK_60860685BF396750 FOREIGN KEY (id) REFERENCES mb_core_sourceinstance (id) ON DELETE CASCADE");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource ADD CONSTRAINT FK_B7B7F16BAED1BBE FOREIGN KEY (wmssource) REFERENCES mb_wms_wmssource (id)");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource ADD CONSTRAINT FK_B7B7F16B727ACA70 FOREIGN KEY (parent_id) REFERENCES mb_wms_wmslayersource (id)");
        } else if ($this->connection->getDatabasePlatform()->getName() === "mysql") {
            $this->addSql("CREATE TABLE fom_profile_basic (uid_id INT NOT NULL, firstName VARCHAR(255) DEFAULT NULL, lastName VARCHAR(255) DEFAULT NULL, notes LONGTEXT DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, street VARCHAR(255) DEFAULT NULL, zipCode VARCHAR(255) DEFAULT NULL, city VARCHAR(255) DEFAULT NULL, country VARCHAR(255) DEFAULT NULL, organizationName VARCHAR(255) DEFAULT NULL, organizationRole VARCHAR(255) DEFAULT NULL, PRIMARY KEY(uid_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE fom_user (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, salt VARCHAR(255) NOT NULL, registrationTime DATETIME DEFAULT NULL, registrationToken VARCHAR(50) DEFAULT NULL, resetTime DATETIME DEFAULT NULL, resetToken VARCHAR(50) DEFAULT NULL, loginFailed DATETIME DEFAULT NULL, loginFailCount INT DEFAULT NULL, UNIQUE INDEX UNIQ_ACA60792F85E0677 (username), UNIQUE INDEX UNIQ_ACA60792E7927C74 (email), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE fom_users_groups (user_id INT NOT NULL, group_id INT NOT NULL, INDEX IDX_15F45F1A76ED395 (user_id), INDEX IDX_15F45F1FE54D947 (group_id), PRIMARY KEY(user_id, group_id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE fom_group (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, UNIQUE INDEX UNIQ_7CE07A482B36786B (title), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_core_contact (id INT AUTO_INCREMENT NOT NULL, person VARCHAR(255) DEFAULT NULL, position VARCHAR(255) DEFAULT NULL, organization VARCHAR(255) DEFAULT NULL, voiceTelephone VARCHAR(255) DEFAULT NULL, facsimileTelephone VARCHAR(255) DEFAULT NULL, electronicMailAddress VARCHAR(255) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, addressType VARCHAR(255) DEFAULT NULL, addressCity VARCHAR(255) DEFAULT NULL, addressStateOrProvince VARCHAR(255) DEFAULT NULL, addressPostCode VARCHAR(255) DEFAULT NULL, addressCountry VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_core_keyword (id INT AUTO_INCREMENT NOT NULL, value VARCHAR(255) NOT NULL, sourceid INT NOT NULL, sourceclass VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_core_layerset (id INT AUTO_INCREMENT NOT NULL, application_id INT DEFAULT NULL, title VARCHAR(128) NOT NULL, INDEX IDX_9D1A22923E030ACD (application_id), UNIQUE INDEX layerset_idx (application_id, title), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_core_srs (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(15) NOT NULL, title VARCHAR(128) NOT NULL, definition VARCHAR(512) NOT NULL, UNIQUE INDEX UNIQ_AD400D955E237E06 (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_core_sourceinstance (id INT AUTO_INCREMENT NOT NULL, layerset INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, weight INT NOT NULL, enabled TINYINT(1) DEFAULT NULL, discr VARCHAR(255) NOT NULL, INDEX IDX_688D0B496A3B1D21 (layerset), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_core_state (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(128) DEFAULT NULL, serverurl VARCHAR(1024) DEFAULT NULL, slug VARCHAR(128) DEFAULT NULL, json LONGTEXT DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_core_element (id INT AUTO_INCREMENT NOT NULL, application_id INT DEFAULT NULL, title VARCHAR(128) NOT NULL, class VARCHAR(1024) NOT NULL, configuration LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', region VARCHAR(255) NOT NULL, enabled TINYINT(1) DEFAULT NULL, weight INT NOT NULL, INDEX IDX_228B0AD3E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_core_source (id INT AUTO_INCREMENT NOT NULL, title VARCHAR(255) DEFAULT NULL, alias VARCHAR(128) DEFAULT NULL, description LONGTEXT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_core_application (id INT AUTO_INCREMENT NOT NULL, owner_id INT DEFAULT NULL, title VARCHAR(128) NOT NULL, slug VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, template VARCHAR(1024) NOT NULL, published TINYINT(1) NOT NULL, screenshot VARCHAR(256) DEFAULT NULL, extra_assets LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', updated DATETIME NOT NULL, UNIQUE INDEX UNIQ_77F4A71D2B36786B (title), UNIQUE INDEX UNIQ_77F4A71D989D9B62 (slug), INDEX IDX_77F4A71D7E3C61F9 (owner_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_wmc_wmc (id INT AUTO_INCREMENT NOT NULL, state INT DEFAULT NULL, contact_id INT DEFAULT NULL, version VARCHAR(10) DEFAULT NULL, wmcid VARCHAR(255) DEFAULT NULL, keywords LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', abstract LONGTEXT DEFAULT NULL, logourl LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', descriptionurl LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', screenshotPath VARCHAR(255) DEFAULT NULL, public TINYINT(1) DEFAULT NULL, UNIQUE INDEX UNIQ_BC0F146BA393D2FB (state), UNIQUE INDEX UNIQ_BC0F146BE7A1254A (contact_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_wms_wmsinstancelayer (id INT AUTO_INCREMENT NOT NULL, wmsinstance INT DEFAULT NULL, wmslayersource INT DEFAULT NULL, parent INT DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, active TINYINT(1) DEFAULT NULL, allowselected TINYINT(1) DEFAULT NULL, selected TINYINT(1) DEFAULT NULL, info TINYINT(1) DEFAULT NULL, allowinfo TINYINT(1) DEFAULT NULL, toggle TINYINT(1) DEFAULT NULL, allowtoggle TINYINT(1) DEFAULT NULL, allowreorder TINYINT(1) DEFAULT NULL, minScale DOUBLE PRECISION DEFAULT NULL, maxScale DOUBLE PRECISION DEFAULT NULL, style VARCHAR(255) DEFAULT NULL, priority INT DEFAULT NULL, INDEX IDX_38F34DB176BBE8FB (wmsinstance), INDEX IDX_38F34DB1714D2654 (wmslayersource), INDEX IDX_38F34DB13D8E604F (parent), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_wms_wmssource (id INT NOT NULL, contact_id INT DEFAULT NULL, originUrl VARCHAR(255) DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, version VARCHAR(255) DEFAULT NULL, onlineResource VARCHAR(255) DEFAULT NULL, fees LONGTEXT DEFAULT NULL, accessConstraints LONGTEXT DEFAULT NULL, layerLimit INT DEFAULT NULL, maxWidth INT DEFAULT NULL, maxHeight INT DEFAULT NULL, exceptionFormats LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', supportSld TINYINT(1) DEFAULT NULL, userLayer TINYINT(1) DEFAULT NULL, userStyle TINYINT(1) DEFAULT NULL, remoteWfs TINYINT(1) DEFAULT NULL, inlineFeature TINYINT(1) DEFAULT NULL, remoteWcs TINYINT(1) DEFAULT NULL, getCapabilities LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', getMap LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', getFeatureInfo LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', describeLayer LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', getLegendGraphic LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', getStyles LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', putStyles LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', username VARCHAR(255) DEFAULT NULL, password VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_F5D6FE8FE7A1254A (contact_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_wms_wmsinstance (id INT NOT NULL, wmssource INT DEFAULT NULL, configuration LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', srs VARCHAR(255) DEFAULT NULL, format VARCHAR(255) DEFAULT NULL, infoformat VARCHAR(255) DEFAULT NULL, exceptionformat VARCHAR(255) DEFAULT NULL, transparency TINYINT(1) DEFAULT NULL, visible TINYINT(1) DEFAULT NULL, opacity INT DEFAULT NULL, proxy TINYINT(1) DEFAULT NULL, tiled TINYINT(1) DEFAULT NULL, INDEX IDX_60860685AED1BBE (wmssource), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE mb_wms_wmslayersource (id INT AUTO_INCREMENT NOT NULL, wmssource INT DEFAULT NULL, parent_id INT DEFAULT NULL, name VARCHAR(255) DEFAULT NULL, title VARCHAR(255) DEFAULT NULL, abstract LONGTEXT DEFAULT NULL, queryable TINYINT(1) DEFAULT NULL, cascaded INT DEFAULT NULL, opaque TINYINT(1) DEFAULT NULL, noSubset TINYINT(1) DEFAULT NULL, fixedWidth INT DEFAULT NULL, fixedHeight INT DEFAULT NULL, latlonBounds LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', boundingBoxes LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', srs LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', styles LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', scale LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', scaleHint LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', attribution LONGTEXT DEFAULT NULL COMMENT '(DC2Type:object)', identifier LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', authority LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', metadataUrl LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', dimension LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', extent LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', dataUrl LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', featureListUrl LONGTEXT DEFAULT NULL COMMENT '(DC2Type:array)', INDEX IDX_B7B7F16BAED1BBE (wmssource), INDEX IDX_B7B7F16B727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("CREATE TABLE owsproxy_log (id INT AUTO_INCREMENT NOT NULL, username VARCHAR(512) NOT NULL, roles LONGTEXT NOT NULL, ip VARCHAR(40) NOT NULL, timestamp DATETIME NOT NULL, request_url LONGTEXT NOT NULL, request_body LONGTEXT NOT NULL, request_method VARCHAR(255) NOT NULL, response_mimetype VARCHAR(255) NOT NULL, response_code INT NOT NULL, response_size INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
            $this->addSql("ALTER TABLE fom_profile_basic ADD CONSTRAINT FK_DE31F81534B549B FOREIGN KEY (uid_id) REFERENCES fom_user (id)");
            $this->addSql("ALTER TABLE fom_users_groups ADD CONSTRAINT FK_15F45F1A76ED395 FOREIGN KEY (user_id) REFERENCES fom_user (id) ON DELETE CASCADE");
            $this->addSql("ALTER TABLE fom_users_groups ADD CONSTRAINT FK_15F45F1FE54D947 FOREIGN KEY (group_id) REFERENCES fom_group (id) ON DELETE CASCADE");
            $this->addSql("ALTER TABLE mb_core_layerset ADD CONSTRAINT FK_9D1A22923E030ACD FOREIGN KEY (application_id) REFERENCES mb_core_application (id)");
            $this->addSql("ALTER TABLE mb_core_sourceinstance ADD CONSTRAINT FK_688D0B496A3B1D21 FOREIGN KEY (layerset) REFERENCES mb_core_layerset (id)");
            $this->addSql("ALTER TABLE mb_core_element ADD CONSTRAINT FK_228B0AD3E030ACD FOREIGN KEY (application_id) REFERENCES mb_core_application (id)");
            $this->addSql("ALTER TABLE mb_core_application ADD CONSTRAINT FK_77F4A71D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES fom_user (id)");
            $this->addSql("ALTER TABLE mb_wmc_wmc ADD CONSTRAINT FK_BC0F146BA393D2FB FOREIGN KEY (state) REFERENCES mb_core_state (id)");
            $this->addSql("ALTER TABLE mb_wmc_wmc ADD CONSTRAINT FK_BC0F146BE7A1254A FOREIGN KEY (contact_id) REFERENCES mb_core_contact (id)");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer ADD CONSTRAINT FK_38F34DB176BBE8FB FOREIGN KEY (wmsinstance) REFERENCES mb_wms_wmsinstance (id)");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer ADD CONSTRAINT FK_38F34DB1714D2654 FOREIGN KEY (wmslayersource) REFERENCES mb_wms_wmslayersource (id)");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer ADD CONSTRAINT FK_38F34DB13D8E604F FOREIGN KEY (parent) REFERENCES mb_wms_wmsinstancelayer (id)");
            $this->addSql("ALTER TABLE mb_wms_wmssource ADD CONSTRAINT FK_F5D6FE8FE7A1254A FOREIGN KEY (contact_id) REFERENCES mb_core_contact (id)");
            $this->addSql("ALTER TABLE mb_wms_wmssource ADD CONSTRAINT FK_F5D6FE8FBF396750 FOREIGN KEY (id) REFERENCES mb_core_source (id) ON DELETE CASCADE");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance ADD CONSTRAINT FK_60860685AED1BBE FOREIGN KEY (wmssource) REFERENCES mb_wms_wmssource (id)");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance ADD CONSTRAINT FK_60860685BF396750 FOREIGN KEY (id) REFERENCES mb_core_sourceinstance (id) ON DELETE CASCADE");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource ADD CONSTRAINT FK_B7B7F16BAED1BBE FOREIGN KEY (wmssource) REFERENCES mb_wms_wmssource (id)");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource ADD CONSTRAINT FK_B7B7F16B727ACA70 FOREIGN KEY (parent_id) REFERENCES mb_wms_wmslayersource (id)");
        } else {
            $this->abortIf(true,
                'The database type "' . $this->connection->getDatabasePlatform()->getName() . " isn't supoorted.");
        }
    }

    public function down(Schema $schema)
    {
        if ($this->connection->getDatabasePlatform()->getName() === "postgresql") {
            $this->addSql("ALTER TABLE fom_profile_basic DROP CONSTRAINT FK_DE31F81534B549B");
            $this->addSql("ALTER TABLE fom_users_groups DROP CONSTRAINT FK_15F45F1A76ED395");
            $this->addSql("ALTER TABLE mb_core_application DROP CONSTRAINT FK_77F4A71D7E3C61F9");
            $this->addSql("ALTER TABLE fom_users_groups DROP CONSTRAINT FK_15F45F1FE54D947");
            $this->addSql("ALTER TABLE mb_wmc_wmc DROP CONSTRAINT FK_BC0F146BE7A1254A");
            $this->addSql("ALTER TABLE mb_wms_wmssource DROP CONSTRAINT FK_F5D6FE8FE7A1254A");
            $this->addSql("ALTER TABLE mb_core_sourceinstance DROP CONSTRAINT FK_688D0B496A3B1D21");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance DROP CONSTRAINT FK_60860685BF396750");
            $this->addSql("ALTER TABLE mb_wmc_wmc DROP CONSTRAINT FK_BC0F146BA393D2FB");
            $this->addSql("ALTER TABLE mb_wms_wmssource DROP CONSTRAINT FK_F5D6FE8FBF396750");
            $this->addSql("ALTER TABLE mb_core_layerset DROP CONSTRAINT FK_9D1A22923E030ACD");
            $this->addSql("ALTER TABLE mb_core_element DROP CONSTRAINT FK_228B0AD3E030ACD");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer DROP CONSTRAINT FK_38F34DB13D8E604F");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance DROP CONSTRAINT FK_60860685AED1BBE");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource DROP CONSTRAINT FK_B7B7F16BAED1BBE");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer DROP CONSTRAINT FK_38F34DB176BBE8FB");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer DROP CONSTRAINT FK_38F34DB1714D2654");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource DROP CONSTRAINT FK_B7B7F16B727ACA70");
            $this->addSql("DROP SEQUENCE fom_user_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE fom_group_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_core_contact_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_core_keyword_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_core_layerset_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_core_srs_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_core_sourceinstance_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_core_state_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_core_element_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_core_source_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_core_application_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_wmc_wmc_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_wms_wmsinstancelayer_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE mb_wms_wmslayersource_id_seq CASCADE");
            $this->addSql("DROP SEQUENCE owsproxy_log_id_seq CASCADE");
            $this->addSql("DROP TABLE fom_profile_basic");
            $this->addSql("DROP TABLE fom_user");
            $this->addSql("DROP TABLE fom_users_groups");
            $this->addSql("DROP TABLE fom_group");
            $this->addSql("DROP TABLE mb_core_contact");
            $this->addSql("DROP TABLE mb_core_keyword");
            $this->addSql("DROP TABLE mb_core_layerset");
            $this->addSql("DROP TABLE mb_core_srs");
            $this->addSql("DROP TABLE mb_core_sourceinstance");
            $this->addSql("DROP TABLE mb_core_state");
            $this->addSql("DROP TABLE mb_core_element");
            $this->addSql("DROP TABLE mb_core_source");
            $this->addSql("DROP TABLE mb_core_application");
            $this->addSql("DROP TABLE mb_wmc_wmc");
            $this->addSql("DROP TABLE mb_wms_wmsinstancelayer");
            $this->addSql("DROP TABLE mb_wms_wmssource");
            $this->addSql("DROP TABLE mb_wms_wmsinstance");
            $this->addSql("DROP TABLE mb_wms_wmslayersource");
            $this->addSql("DROP TABLE owsproxy_log");
        } else if ($this->connection->getDatabasePlatform()->getName() === "oracle") {
            $this->addSql("ALTER TABLE fom_profile_basic DROP CONSTRAINT FK_DE31F81534B549B");
            $this->addSql("ALTER TABLE fom_users_groups DROP CONSTRAINT FK_15F45F1A76ED395");
            $this->addSql("ALTER TABLE mb_core_application DROP CONSTRAINT FK_77F4A71D7E3C61F9");
            $this->addSql("ALTER TABLE fom_users_groups DROP CONSTRAINT FK_15F45F1FE54D947");
            $this->addSql("ALTER TABLE mb_wmc_wmc DROP CONSTRAINT FK_BC0F146BE7A1254A");
            $this->addSql("ALTER TABLE mb_wms_wmssource DROP CONSTRAINT FK_F5D6FE8FE7A1254A");
            $this->addSql("ALTER TABLE mb_core_sourceinstance DROP CONSTRAINT FK_688D0B496A3B1D21");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance DROP CONSTRAINT FK_60860685BF396750");
            $this->addSql("ALTER TABLE mb_wmc_wmc DROP CONSTRAINT FK_BC0F146BA393D2FB");
            $this->addSql("ALTER TABLE mb_wms_wmssource DROP CONSTRAINT FK_F5D6FE8FBF396750");
            $this->addSql("ALTER TABLE mb_core_layerset DROP CONSTRAINT FK_9D1A22923E030ACD");
            $this->addSql("ALTER TABLE mb_core_element DROP CONSTRAINT FK_228B0AD3E030ACD");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer DROP CONSTRAINT FK_38F34DB13D8E604F");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance DROP CONSTRAINT FK_60860685AED1BBE");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource DROP CONSTRAINT FK_B7B7F16BAED1BBE");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer DROP CONSTRAINT FK_38F34DB176BBE8FB");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer DROP CONSTRAINT FK_38F34DB1714D2654");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource DROP CONSTRAINT FK_B7B7F16B727ACA70");
            $this->addSql("DROP SEQUENCE fom_user_id_seq");
            $this->addSql("DROP SEQUENCE fom_group_id_seq");
            $this->addSql("DROP SEQUENCE mb_core_contact_id_seq");
            $this->addSql("DROP SEQUENCE mb_core_keyword_id_seq");
            $this->addSql("DROP SEQUENCE mb_core_layerset_id_seq");
            $this->addSql("DROP SEQUENCE mb_core_srs_id_seq");
            $this->addSql("DROP SEQUENCE mb_core_sourceinstance_id_seq");
            $this->addSql("DROP SEQUENCE mb_core_state_id_seq");
            $this->addSql("DROP SEQUENCE mb_core_element_id_seq");
            $this->addSql("DROP SEQUENCE mb_core_source_id_seq");
            $this->addSql("DROP SEQUENCE mb_core_application_id_seq");
            $this->addSql("DROP SEQUENCE mb_wmc_wmc_id_seq");
            $this->addSql("DROP SEQUENCE mb_wms_wmsinstancelayer_id_seq");
            $this->addSql("DROP SEQUENCE mb_wms_wmslayersource_id_seq");
            $this->addSql("DROP SEQUENCE owsproxy_log_id_seq");
            $this->addSql("DROP TABLE fom_profile_basic");
            $this->addSql("DROP TABLE fom_user");
            $this->addSql("DROP TABLE fom_users_groups");
            $this->addSql("DROP TABLE fom_group");
            $this->addSql("DROP TABLE mb_core_contact");
            $this->addSql("DROP TABLE mb_core_keyword");
            $this->addSql("DROP TABLE mb_core_layerset");
            $this->addSql("DROP TABLE mb_core_srs");
            $this->addSql("DROP TABLE mb_core_sourceinstance");
            $this->addSql("DROP TABLE mb_core_state");
            $this->addSql("DROP TABLE mb_core_element");
            $this->addSql("DROP TABLE mb_core_source");
            $this->addSql("DROP TABLE mb_core_application");
            $this->addSql("DROP TABLE mb_wmc_wmc");
            $this->addSql("DROP TABLE mb_wms_wmsinstancelayer");
            $this->addSql("DROP TABLE mb_wms_wmssource");
            $this->addSql("DROP TABLE mb_wms_wmsinstance");
            $this->addSql("DROP TABLE mb_wms_wmslayersource");
            $this->addSql("DROP TABLE owsproxy_log");
        } else if ($this->connection->getDatabasePlatform()->getName() === "mysql") {
            $this->addSql("ALTER TABLE fom_profile_basic DROP FOREIGN KEY FK_DE31F81534B549B");
            $this->addSql("ALTER TABLE fom_users_groups DROP FOREIGN KEY FK_15F45F1A76ED395");
            $this->addSql("ALTER TABLE mb_core_application DROP FOREIGN KEY FK_77F4A71D7E3C61F9");
            $this->addSql("ALTER TABLE fom_users_groups DROP FOREIGN KEY FK_15F45F1FE54D947");
            $this->addSql("ALTER TABLE mb_wmc_wmc DROP FOREIGN KEY FK_BC0F146BE7A1254A");
            $this->addSql("ALTER TABLE mb_wms_wmssource DROP FOREIGN KEY FK_F5D6FE8FE7A1254A");
            $this->addSql("ALTER TABLE mb_core_sourceinstance DROP FOREIGN KEY FK_688D0B496A3B1D21");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance DROP FOREIGN KEY FK_60860685BF396750");
            $this->addSql("ALTER TABLE mb_wmc_wmc DROP FOREIGN KEY FK_BC0F146BA393D2FB");
            $this->addSql("ALTER TABLE mb_wms_wmssource DROP FOREIGN KEY FK_F5D6FE8FBF396750");
            $this->addSql("ALTER TABLE mb_core_layerset DROP FOREIGN KEY FK_9D1A22923E030ACD");
            $this->addSql("ALTER TABLE mb_core_element DROP FOREIGN KEY FK_228B0AD3E030ACD");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer DROP FOREIGN KEY FK_38F34DB13D8E604F");
            $this->addSql("ALTER TABLE mb_wms_wmsinstance DROP FOREIGN KEY FK_60860685AED1BBE");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource DROP FOREIGN KEY FK_B7B7F16BAED1BBE");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer DROP FOREIGN KEY FK_38F34DB176BBE8FB");
            $this->addSql("ALTER TABLE mb_wms_wmsinstancelayer DROP FOREIGN KEY FK_38F34DB1714D2654");
            $this->addSql("ALTER TABLE mb_wms_wmslayersource DROP FOREIGN KEY FK_B7B7F16B727ACA70");
            $this->addSql("DROP TABLE fom_profile_basic");
            $this->addSql("DROP TABLE fom_user");
            $this->addSql("DROP TABLE fom_users_groups");
            $this->addSql("DROP TABLE fom_group");
            $this->addSql("DROP TABLE mb_core_contact");
            $this->addSql("DROP TABLE mb_core_keyword");
            $this->addSql("DROP TABLE mb_core_layerset");
            $this->addSql("DROP TABLE mb_core_srs");
            $this->addSql("DROP TABLE mb_core_sourceinstance");
            $this->addSql("DROP TABLE mb_core_state");
            $this->addSql("DROP TABLE mb_core_element");
            $this->addSql("DROP TABLE mb_core_source");
            $this->addSql("DROP TABLE mb_core_application");
            $this->addSql("DROP TABLE mb_wmc_wmc");
            $this->addSql("DROP TABLE mb_wms_wmsinstancelayer");
            $this->addSql("DROP TABLE mb_wms_wmssource");
            $this->addSql("DROP TABLE mb_wms_wmsinstance");
            $this->addSql("DROP TABLE mb_wms_wmslayersource");
            $this->addSql("DROP TABLE owsproxy_log");
        } else {
            $this->abortIf(true,
                'The database type "' . $this->connection->getDatabasePlatform()->getName() . " isn't supoorted.");
        }
    }

}
